"""inital mirtaions

Revision ID: 873d968dc6f8
Revises: 219352e1f5e8
Create Date: 2024-11-20 13:13:41.333660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873d968dc6f8'
down_revision = '219352e1f5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
